version: "3"
services:
  postgres:
    container_name: postgres_springtest
    image: postgres:12
    environment:
      POSTGRES_DB: springtest
      POSTGRES_USER: springtest
      POSTGRES_PASSWORD: springtest
    ports:
      - "5444:5432"
