@startuml
skinparam dpi 110
skinparam style strictuml
autonumber

actor User #ebcebc

participant Frontend #ebaeba
'participant Backend #6db33f

box "Backend" #eeeeee
 participant Controller #6db33f
 participant Service #6db33f
' participant Repository #6db33f
 participant Repository #6db33f
end box

database PostgreSQL #aaccee

User -> Frontend : Enter request text
Frontend -> Controller : Send data in JSON format
Controller -> Service : get list
Service -> Repository : get data from DB
Repository --> PostgreSQL : SQL statements
PostgreSQL --> Repository : articles data(records)
Repository --> Service : list of objects
Service --> Controller : list of objects
Controller --> Frontend : Send result/response in JSON
Frontend --> User: Show result

@enduml
